[package]
name = "lab1"
version = "0.1.0"
# QUIZ: what are rust editions?
edition = "2021"

[dependencies]
rand = "0.8"
clearscreen = "2.0.0"
# QUIZ: how can you add the clap crate with the derive feature?
